version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python app.py
    # tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - redis
    env_file: .env.dev
  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - .:/code
    depends_on:
      - web
    env_file: .env.dev
  flower:
    build: .
    command: celery flower --port=5555 --broker=$CELERY_BROKER_URL
    ports:
      - 5555:5555
    depends_on:
      - worker
    env_file: .env.dev
  pytest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pytest --cov=.
    volumes:
      - .:/code
    depends_on:
      - web
    env_file: .env.dev