version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - .:/code
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
  flower:
    build: .
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery flower --port=5555 --broker=$CELERY_BROKER_URL
    ports:
      - 5555:5555
    depends_on:
      - redis